import './functions/browser.js';
import './functions/cards.js';
import './functions/countdown.js';
import './functions/datepicker.js';
import './functions/html.js';
import './functions/paging.js';
import './functions/prototyping.js';
import './functions/setup.js';
import './functions/sidenav.js';
