<?php
    include_once $_SERVER['DOCUMENT_ROOT'].'/resources/dargmuesli/cache/enabled.php';
    include_once $_SERVER['DOCUMENT_ROOT'].'/resources/dargmuesli/base/skeleton.php';

    lastModified(getPageModTime());

    $skeletonDescription = 'Generated by javadoc (1.8.0_25) on Sat Feb 07 16:09:52 CET 2015';
    $skeletonContent = '
    <iframe src="layout/data/doc/index.html"></iframe>';

    outputHtml($skeletonDescription, $skeletonContent);
